# Generated by Django 3.0.8 on 2020-07-06 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opentrellisFront', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
